[package]
<<<<<<< HEAD
name = "bespec"
version = "1.4.0-rc1"
=======
name = "beanal"
version = "1.3.0-rc3"
>>>>>>> 9a914ae315a67e8f19462fc84aaac21478219d4b
edition = "2021"
authors = ["BeSpec-Dev"]
description = "A lightweight, highly configurable, real-time audio spectrum visualizer"

[build-dependencies]
winres = "0.1"

[dependencies]
# Audio capture and processing
cpal = "0.15"
realfft = "3.3"
num-complex = "0.4"
lazy_static = "1.4"
directories = "5.0"

# Data logging
tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["time", "env-filter"] }
tracing-appender = "0.2"
time = { version = "0.3", features = ["formatting", "macros", "local-offset"] }
libc = "0.2"

# Icon Generation
image = {version = "0.24", default-features = false, features = ["png", "jpeg"] }

# GUI framework
eframe = "0.29"
egui = "0.29"

# Thread communication and syncronization
crossbeam-channel = "0.5"

# Serialization for settings
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# == Media Integration ==
# Windows: Uses the official Microsoft crate
[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.52", features = [
    "Foundation_Collections",
    "Media_Control",
    "Storage_Streams",
] }
tokio = { version = "1.0", default-features = false, features = ["rt", "time", "sync"] }

# Linux: Uses the MPRIS standard via D-Bus
[target.'cfg(target_os = "linux")'.dependencies]
mpris = "2.0"
ureq = "2.9"

# macOS: Uses private MediaRemote framework bindings
[target.'cfg(target_os = "macos")'.dependencies]
mediaremote-rs = "0.1"
base64 = "0.22"
ureq = "2.9"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
# Space saving options
# Strip = true removes symbol information during a crash
strip = true
# panic = "abort" reduces binary size by disabling unwinding
panic = "abort"

# Explicitly declare the test harness binary
[[bin]]
name = "media_test"
path = "src/bin/media_test.rs"

# Explicitly declare the main binary (BeSpec)
[[bin]]
name = "bespec"
path = "src/main.rs"